#!/bin/bash

echo "🚀 PRONOTE+ - LANCEMENT IMMÉDIAT"
echo "================================"
echo ""
echo "Option 1 : Interface Web (Recommandé)"
echo "------------------------------------"
echo "1. Exécutez : npm run dev:vite"
echo "2. Ouvrez : http://localhost:3001/"
echo ""
echo "Option 2 : Application Desktop"
echo "----------------------------"
echo "1. Exécutez : npm run dev"
echo "2. L'application Electron se lancera"
echo ""
echo "📊 Statistiques du projet :"
echo "- 9 modules fonctionnels complets"
echo "- Interface React moderne"
echo "- 765 packages installés"
echo "- Build multi-plateforme prêt"
